# Generated by Django 3.2.4 on 2021-06-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU_No', models.CharField(max_length=50)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='product')),
            ],
        ),
    ]
